apiVersion: monitoring.googleapis.com/v1
kind: PodMonitoring
metadata:
  name: prometheus-example
  namespace: prometheus-demo
spec:
  selector:
    matchLabels:
      app: prometheus-example
  endpoints:
  - port: metrics
    interval: 30s